using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Aprillz.MewUI.Generators;

/// <summary>
/// Rewrites dotted binding lambdas into explicit BindingPath segment chains.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BindingPathGenerator : IIncrementalGenerator
{
    private const string MARKER_HINT_NAME = "BindingPathGeneratorMarker.g.cs";
    private const string ATTRIBUTE_HINT_NAME = "InterceptsLocationAttribute.g.cs";
    private const string INTERCEPTOR_HINT_NAME = "BindingPathInterceptors.g.cs";

    internal static readonly DiagnosticDescriptor UnsupportedGetter = new(
        id: "MEWG001",
        title: "Binding getter cannot be split into path segments",
        messageFormat: "'{0}' is not a binding path",
        category: "MewUI.Binding",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "A binding getter must walk members, indexers with constant arguments, and casts. Move computation into a convert delegate, or build the path with an explicit ThenNotifying chain.");

    // MewUI.Analyzers probes this type to tell whether this generator ran in the compilation, so
    // the fully qualified name is a contract between the two assemblies.
    private const string MARKER_SOURCE = """
        // <auto-generated/>
        namespace Aprillz.MewUI.Generated
        {
            internal static class BindingPathGeneratorMarker
            {
            }
        }
        """;

    private const string ATTRIBUTE_SOURCE = """
        // <auto-generated/>
        namespace System.Runtime.CompilerServices
        {
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
            internal sealed class InterceptsLocationAttribute : global::System.Attribute
            {
                public InterceptsLocationAttribute(int version, string data)
                {
                }
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(postInitialization =>
        {
            postInitialization.AddSource(MARKER_HINT_NAME, MARKER_SOURCE);
            postInitialization.AddSource(ATTRIBUTE_HINT_NAME, ATTRIBUTE_SOURCE);
        });

        var calls = context.SyntaxProvider
            .CreateSyntaxProvider(IsCandidate, Transform)
            .Where(static call => call != null)
            .Collect();

        context.RegisterSourceOutput(calls, Emit!);
    }

    private static bool IsCandidate(SyntaxNode node, CancellationToken cancellationToken)
        => node is InvocationExpressionSyntax
        {
            Expression: MemberAccessExpressionSyntax
            {
                Name: IdentifierNameSyntax { Identifier.ValueText: "Bind" or "SetBinding" },
            },
        };

    private static BindingCall? Transform(
        GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        if (context.SemanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol
            is not IMethodSymbol method)
        {
            return null;
        }

        var owner = method.ContainingType;
        bool isExtension = method.Name == "Bind";
        if (isExtension
            ? owner.ToDisplayString() != "Aprillz.MewUI.Controls.BindingExtensions"
            : owner.ToDisplayString() != "Aprillz.MewUI.Controls.MewObject")
        {
            return null;
        }

        var parameters = method.ReducedFrom?.Parameters ?? method.Parameters;
        if (IndexOfParameter(parameters, "getter") < 0)
        {
            return null;
        }

        var arguments = invocation.ArgumentList.Arguments;
        if (FindArgument(arguments, parameters, "setter", isExtension) != null)
        {
            return null;
        }

        if (FindArgument(arguments, parameters, "getter", isExtension)
            is not AnonymousFunctionExpressionSyntax getter)
        {
            return null;
        }

        var steps = BindingChain.TryReadSteps(context.SemanticModel, getter);
        if (steps == null)
        {
            // A single member access is what the runtime infers on its own; anything else that is
            // not a readable path would fail at runtime, so surface it now.
            return IsSingleMemberAccess(getter)
                ? null
                : BindingCall.Unsupported(getter.GetLocation(), getter.ToString());
        }

        var segments = BindingChain.TryResolveSegments(
            context.SemanticModel.Compilation, context.SemanticModel, steps);
        if (segments == null)
        {
            return BindingCall.Unsupported(getter.GetLocation(), getter.ToString());
        }

        // A single member is what the runtime reads on its own. Intercepting is only worth it when
        // a setter can be synthesized, which is what lets a TwoWay target write back without one.
        if (steps.Count == 1
            && (segments[0].Kind != BindingSegmentKind.Notifying || segments[0].SetterBody == null))
        {
            return null;
        }

        var location = context.SemanticModel.GetInterceptableLocation(invocation, cancellationToken);
        if (location == null)
        {
            return null;
        }

        var receiver = ((MemberAccessExpressionSyntax)invocation.Expression).Expression;
        if (context.SemanticModel.GetTypeInfo(receiver, cancellationToken).Type is not ITypeSymbol
            receiverType)
        {
            return null;
        }

        var sourceType = parameters[IndexOfParameter(parameters, "source")].Type;
        var getterDelegate = (INamedTypeSymbol)parameters[IndexOfParameter(parameters, "getter")].Type;
        var propertyType = (INamedTypeSymbol)parameters[IndexOfParameter(parameters, "property")].Type;

        return BindingCall.Interception(
            location.Version,
            location.Data,
            isExtension,
            IndexOfParameter(parameters, "convert") >= 0,
            Display(receiverType),
            Display(Substitute(sourceType, method)),
            Display(Substitute(propertyType.TypeArguments[0], method)),
            Display(Substitute(getterDelegate.TypeArguments[1], method)),
            segments);
    }

    private static bool IsSingleMemberAccess(AnonymousFunctionExpressionSyntax lambda)
        => lambda.Body is MemberAccessExpressionSyntax access
            && access.IsKind(SyntaxKind.SimpleMemberAccessExpression)
            && access.Expression is IdentifierNameSyntax;

    private static ITypeSymbol Substitute(ITypeSymbol type, IMethodSymbol method)
    {
        if (type is not ITypeParameterSymbol parameter || method.ReducedFrom == null)
        {
            return type;
        }

        var definition = method.ReducedFrom;
        for (int index = 0; index < definition.TypeParameters.Length; index++)
        {
            if (SymbolEqualityComparer.Default.Equals(definition.TypeParameters[index], parameter))
            {
                return method.TypeArguments[index];
            }
        }

        return type;
    }

    private static int IndexOfParameter(ImmutableArray<IParameterSymbol> parameters, string name)
    {
        for (int index = 0; index < parameters.Length; index++)
        {
            if (parameters[index].Name == name)
            {
                return index;
            }
        }

        return -1;
    }

    private static ExpressionSyntax? FindArgument(
        SeparatedSyntaxList<ArgumentSyntax> arguments,
        ImmutableArray<IParameterSymbol> parameters,
        string name,
        bool isExtension)
    {
        // A reduced extension call drops the receiver, so positional indexes shift by one.
        int target = IndexOfParameter(parameters, name) - (isExtension ? 1 : 0);
        for (int index = 0; index < arguments.Count; index++)
        {
            var argument = arguments[index];
            if (argument.NameColon is NameColonSyntax named)
            {
                if (named.Name.Identifier.ValueText == name)
                {
                    return argument.Expression;
                }
            }
            else if (index == target)
            {
                return argument.Expression;
            }
        }

        return null;
    }

    private static string Display(ITypeSymbol type)
        => type.WithNullableAnnotation(NullableAnnotation.NotAnnotated)
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static void Emit(SourceProductionContext context, ImmutableArray<BindingCall?> calls)
    {
        var interceptions = new List<BindingCall>();
        foreach (var call in calls)
        {
            if (call == null)
            {
                continue;
            }

            if (call.UnsupportedLocation != null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    UnsupportedGetter, call.UnsupportedLocation, call.UnsupportedText));
                continue;
            }

            interceptions.Add(call);
        }

        if (interceptions.Count == 0)
        {
            return;
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Aprillz.MewUI.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class BindingPathInterceptors");
        builder.AppendLine("    {");

        // Paths live in a nullable-oblivious region so a nullable intermediate does not trip the
        // class constraint on the next segment. Suppressing per expression is not an option: a
        // parenthesized member access followed by ! parses as a cast.
        builder.AppendLine("#nullable disable");
        for (int index = 0; index < interceptions.Count; index++)
        {
            AppendPath(builder, interceptions[index], index);
        }

        builder.AppendLine("#nullable restore");
        builder.AppendLine();

        for (int index = 0; index < interceptions.Count; index++)
        {
            AppendInterceptor(builder, interceptions[index], index);
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource(INTERCEPTOR_HINT_NAME, SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static void AppendPath(StringBuilder builder, BindingCall call, int index)
    {
        builder.AppendLine(
            $"        private static readonly global::Aprillz.MewUI.BindingPath<{call.SourceType}, {call.ValueType}> _path{index} =");
        builder.AppendLine(
            $"            global::Aprillz.MewUI.BindingPath.From<{call.SourceType}>()");
        for (int segment = 0; segment < call.Segments!.Count; segment++)
        {
            bool isLeaf = segment == call.Segments.Count - 1;
            builder.AppendLine(
                "                " + FormatSegment(call.Segments[segment])
                    + (isLeaf ? ";" : string.Empty));
        }

        builder.AppendLine();
    }

    private static void AppendInterceptor(StringBuilder builder, BindingCall call, int index)
    {
        string path = $"_path{index}";
        builder.AppendLine(
            $"        [global::System.Runtime.CompilerServices.InterceptsLocation({call.Version}, \"{call.Data}\")]");

        string returnType = call.IsExtension ? call.ReceiverType : "void";
        string name = call.IsExtension ? $"Bind{index}" : $"SetBinding{index}";
        builder.AppendLine($"        internal static {returnType} {name}(");
        builder.AppendLine($"            this {call.ReceiverType} target,");
        builder.AppendLine($"            global::Aprillz.MewUI.MewProperty<{call.PropertyType}> property,");
        builder.AppendLine($"            {call.SourceType} source,");
        builder.AppendLine(
            $"            global::System.Func<{call.SourceType}, {call.ValueType}> getter,");
        if (call.HasConvert)
        {
            builder.AppendLine(
                $"            global::System.Func<{call.ValueType}, {call.PropertyType}> convert,");
        }

        builder.AppendLine(
            $"            global::System.Action<{call.SourceType}, {call.ValueType}>? setter = null,");
        if (call.HasConvert)
        {
            builder.AppendLine(
                $"            global::System.Func<{call.PropertyType}, {call.ValueType}>? convertBack = null,");
        }

        builder.AppendLine("            global::Aprillz.MewUI.BindingMode? mode = null,");
        builder.AppendLine("            string? getterExpression = null)");
        builder.AppendLine("        {");
        builder.AppendLine(call.HasConvert
            ? $"            target.SetBinding(property, source, {path}, convert, convertBack, mode, default!);"
            : $"            target.SetBinding(property, source, {path}, mode, default!);");
        if (call.IsExtension)
        {
            builder.AppendLine("            return target;");
        }

        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private static string FormatSegment(BindingSegment segment)
    {
        if (segment.Kind == BindingSegmentKind.MewProperty)
        {
            return $".Then({segment.MewPropertyReference})";
        }

        if (segment.Kind == BindingSegmentKind.Indexed)
        {
            return $".ThenIndexed(static value => {segment.Expression})";
        }

        if (segment.Kind != BindingSegmentKind.Notifying)
        {
            return $".Then(static value => {segment.Expression})";
        }

        return segment.SetterBody == null
            ? $".ThenNotifying(static value => {segment.Expression})"
            : $".ThenNotifying(static value => {segment.Expression}, static (value, newValue) => {segment.SetterBody})";
    }

    private sealed class BindingCall
    {
        private BindingCall()
        {
        }

        public int Version { get; private set; }

        public string Data { get; private set; } = string.Empty;

        public bool IsExtension { get; private set; }

        public bool HasConvert { get; private set; }

        public string ReceiverType { get; private set; } = string.Empty;

        public string SourceType { get; private set; } = string.Empty;

        public string PropertyType { get; private set; } = string.Empty;

        public string ValueType { get; private set; } = string.Empty;

        public List<BindingSegment>? Segments { get; private set; }

        public Location? UnsupportedLocation { get; private set; }

        public string? UnsupportedText { get; private set; }

        public static BindingCall Unsupported(Location location, string text)
            => new() { UnsupportedLocation = location, UnsupportedText = text };

        public static BindingCall Interception(
            int version,
            string data,
            bool isExtension,
            bool hasConvert,
            string receiverType,
            string sourceType,
            string propertyType,
            string valueType,
            List<BindingSegment> segments)
            => new()
            {
                Version = version,
                Data = data,
                IsExtension = isExtension,
                HasConvert = hasConvert,
                ReceiverType = receiverType,
                SourceType = sourceType,
                PropertyType = propertyType,
                ValueType = valueType,
                Segments = segments,
            };
    }
}
