<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Aprillz.MewUI.WebView2.Win32.Sample</RootNamespace>
    <AssemblyName>Aprillz.MewUI.WebView2.Win32.Sample</AssemblyName>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MewUI\MewUI.csproj" />
    <ProjectReference Include="..\..\src\MewUI.Platform.Win32\MewUI.Platform.Win32.csproj" />
    <ProjectReference Include="..\..\src\MewUI.Backend.Gdi\MewUI.Backend.Gdi.csproj" />
    <ProjectReference Include="..\..\src\MewUI.Backend.Direct2D\MewUI.Backend.Direct2D.csproj" />
    <ProjectReference Include="..\..\src\MewUI.Backend.MewVG.Win32\MewUI.Backend.MewVG.Win32.csproj" />
    <ProjectReference Include="..\..\extensions\MewUI.WebView2.Win32\MewUI.WebView2.Win32.csproj" />
  </ItemGroup>

  <Import Project="..\..\build\Aprillz.MewUI.targets" />

</Project>
