// Generates the shim fallback project (app reference, no app Main) under the app's obj folder.
// The shim source mirrors tools/vscode-mewui/src/session.ts SHIM_PROGRAM_SOURCE.
package com.aprillz.mewui.preview

import com.google.gson.JsonObject
import java.io.File
import java.util.concurrent.TimeUnit

object ShimProject {
    fun generate(projectPath: String): String {
        val shimDir = File(File(projectPath).parentFile, "obj/mewui-preview/shim")
        shimDir.mkdirs()

        val targetFramework = queryTargetFramework(projectPath) ?: "net8.0"
        val referencePath = File(projectPath).absolutePath.replace('\\', '/')
        File(shimDir, "MewUIPreviewShim.csproj").writeText(
            """
            <Project Sdk="Microsoft.NET.Sdk">

              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>$targetFramework</TargetFramework>
                <Nullable>disable</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
              </PropertyGroup>

              <ItemGroup>
                <ProjectReference Include="$referencePath" />
              </ItemGroup>

            </Project>
            """.trimIndent() + "\n",
        )
        File(shimDir, "Program.cs").writeText(SHIM_PROGRAM_SOURCE)
        return File(shimDir, "MewUIPreviewShim.csproj").absolutePath
    }

    private fun queryTargetFramework(projectPath: String): String? {
        return try {
            val process = ProcessBuilder(
                "dotnet", "msbuild", projectPath,
                "-getProperty:TargetFramework", "-getProperty:TargetFrameworks",
            ).redirectErrorStream(false).start()
            val output = process.inputStream.bufferedReader().readText()
            if (!process.waitFor(30, TimeUnit.SECONDS) || process.exitValue() != 0) {
                return null
            }
            val properties = PreviewProtocol.gson.fromJson(output, JsonObject::class.java)
                .getAsJsonObject("Properties") ?: return null
            val single = properties.get("TargetFramework")?.asString?.trim()
            if (!single.isNullOrEmpty()) {
                return single
            }
            properties.get("TargetFrameworks")?.asString
                ?.split(';')
                ?.map { it.trim() }
                ?.firstOrNull { it.isNotEmpty() }
        } catch (_: Exception) {
            null
        }
    }

    // The generated shim entry point: loads every managed assembly in the output folder (forcing
    // module initializers so the injected preview bootstrap registers), registers the per-OS
    // default platform/backend reflectively, and runs an empty window.
    private val SHIM_PROGRAM_SOURCE = """
        // Auto-generated by the MewUI preview extension for shim fallback sessions. Do not edit.
        using System;
        using System.IO;
        using System.Reflection;
        using System.Runtime.CompilerServices;

        using Aprillz.MewUI;
        using Aprillz.MewUI.Controls;

        internal static class Program
        {
            private static void Main()
            {
                LoadLocalAssemblies();
                RegisterPlatform();
                Application.Run(new Window { Title = "MewUI preview shim" });
            }

            private static void LoadLocalAssemblies()
            {
                foreach (var file in Directory.GetFiles(AppContext.BaseDirectory, "*.dll"))
                {
                    try
                    {
                        var loaded = Assembly.Load(AssemblyName.GetAssemblyName(file));
                        // Force module initializers so the preview bootstrap injected into the app
                        // assembly registers even though the shim never calls into app code.
                        RuntimeHelpers.RunModuleConstructor(loaded.ManifestModule.ModuleHandle);
                    }
                    catch
                    {
                        // Native or otherwise unloadable images; the scan proceeds with what did load.
                    }
                }
            }

            private static void RegisterPlatform()
            {
                if (OperatingSystem.IsWindows())
                {
                    Register("Aprillz.MewUI.Platform.Win32", "Aprillz.MewUI.Win32Platform");
                    Register("Aprillz.MewUI.Backend.Gdi", "Aprillz.MewUI.GdiBackend");
                }
                else if (OperatingSystem.IsLinux())
                {
                    Register("Aprillz.MewUI.Platform.X11", "Aprillz.MewUI.X11Platform");
                    Register("Aprillz.MewUI.Backend.MewVG.X11", "Aprillz.MewUI.MewVGX11Backend");
                }
                else if (OperatingSystem.IsMacOS())
                {
                    Register("Aprillz.MewUI.Platform.MacOS", "Aprillz.MewUI.MacOSPlatform");
                    Register("Aprillz.MewUI.Backend.MewVG.MacOS", "Aprillz.MewUI.MewVGMacOSBackend");
                }
            }

            private static void Register(string assemblyName, string typeName)
            {
                try
                {
                    Assembly.Load(assemblyName)
                        .GetType(typeName)?
                        .GetMethod("Register", BindingFlags.Public | BindingFlags.Static)?
                        .Invoke(null, null);
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine("[mewui-preview-shim] " + typeName + " registration failed: " + ex.Message);
                }
            }
        }
    """.trimIndent() + "\n"
}
